-- est const behavior (and mutable by default)

print("esting const/mutable behavior...")

function fails(code, msg)
    f, err = loadstring(code)
    -- [] Workaround: loadstring currently returns error string as first arg 
    -- for syntax errors generated by check_readonly.
    if type(f) == "string" then
         err = f
         f = nil
    end

    if f then
        print("Expected failure for: " .. msg)
        os.exit(1)
    end
    
    if not is string.find(err, "attempt to assign to const variable") then
        print("Wrong error for: " .. msg .. ": " .. err)
        os.exit(1)
    end
end

function succeeds(code, msg)
    f, err = loadstring(code)
    if not is f then
        print("Expected success for: " .. msg .. ". Error: " .. tostring(err))
        os.exit(1)
    end
    f()
end

-- est 1: eassign implicit local (should SUCCEED now)
succeeds("a = 1; a = 2", "reassign implicit")

-- est 2: eassign loop variable (should SUCCEED now)
succeeds("for i=1,10 do i=5 break end", "reassign loop var")

-- est 3: eassign parameter (should SUCCEED now)
succeeds("function f(x) x=2 end; f(1)", "reassign parameter")

-- est 4: Const variable reassignment (should FL)
fails("const c = 1; c = 2", "reassign const")

-- est 5: Multiple consts
fails("const c, d = 1, 2; d = 3", "reassign second const")

print("Const/Mutable tests passed")
